### ISSUE TITLE
pow(0+0i, 1+0i) === NaN

### ISSUE THREAD

**Issue by tlbtlbtlb** [patrickroberts/complex-js#5]
```
> C = require('complex-js')
> C(0,0).pow(C(1,0))
n { abs: 0, arg: NaN }
> C(0,0).pow(C(1,0)).real
NaN
> C(0,0).pow(C(1,0)).imag
NaN
```

The case of pow(0+0i, ...) needs to be handled specially, since you can't compute the angle. I think the logic should be:
```
   if (y.real === 0 && y.imag === 0) {
    return C(1, 0)
   }
   else if (x.real === 0 && x.imag === 0) {
    return C(0, 0)
  }
  else {
    ... existing logic ...
   }
```

**Comment by patrickroberts** [comment]
@tlbtlbtlb Thank you for highlighting this issue. I recall having noticed this a year or so ago, but I'm afraid I'm no longer actively maintaining this module. I may publish a new version in the future, but it's been in development for over a year now and I haven't had much time to work on it.

However, given the simplicity of this issue, if you'd like me to publish a patch for this, I can do so within a week. For the long term, I would highly recommend considering another complex math library to use, though. If you need this module specifically for the math expression compiler, I have been working on a new one, and it would be pretty easy to adapt to any library.

Again, thank you for bringing this to my attention.
